name: reagents_pred
channels:
  - rdkit
  - pytorch
  - intel
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - _tflow_select=2.3.0
  - absl-py=0.15.0
  - aiohttp=3.7.4.post0
  - anyio=2.2.0
  - argon2-cffi=20.1.0
  - astor=0.8.1
  - astunparse=1.6.3
  - async-timeout=3.0.1
  - async_generator=1.10
  - attrs=21.4.0
  - babel=2.9.1
  - backcall=0.2.0
  - blas=1.0
  - bleach=4.1.0
  - blinker=1.4
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.18.1
  - ca-certificates=2022.6.15
  - cachetools=4.2.2
  - cairo=1.16.0
  - certifi=2021.5.30
  - cffi=1.14.6
  - chardet=4.0.0
  - charset-normalizer=2.0.4
  - click=8.0.3
  - colorama=0.4.4
  - contextvars=2.4
  - cryptography=3.4.7
  - cudatoolkit=10.2.89
  - cycler=0.11.0
  - daal=2021.5.3
  - daal4py=2021.5.3
  - dal=2021.5.3
  - dataclasses=0.8
  - dbus=1.13.18
  - decorator=5.1.1
  - defusedxml=0.7.1
  - entrypoints=0.3
  - expat=2.4.4
  - fontconfig=2.13.1
  - freetype=2.11.0
  - future=0.18.2
  - gast=0.3.3
  - glib=2.69.1
  - google-auth=1.35.0
  - google-auth-oauthlib=0.4.4
  - google-pasta=0.2.0
  - grpcio=1.31.0
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - h5py=2.10.0
  - hdf5=1.10.6
  - icc_rt=2020.3
  - icu=58.2
  - idna=3.3
  - idna_ssl=1.1.0
  - immutables=0.16
  - importlib-metadata=4.8.1
  - intel-openmp=2022.0.1
  - intelpython=2022.1.0
  - ipykernel=5.3.4
  - ipython=7.16.1
  - ipython_genutils=0.2.0
  - jedi=0.17.0
  - jinja2=3.0.3
  - jpeg=9e
  - json5=0.9.6
  - jsonschema=3.0.2
  - jupyter_client=7.1.2
  - jupyter_core=4.8.1
  - jupyter_server=1.4.1
  - jupyterlab=3.2.1
  - jupyterlab_pygments=0.1.2
  - jupyterlab_server=2.10.3
  - keras-preprocessing=1.1.2
  - kiwisolver=1.3.1
  - lcms2=2.12
  - ld_impl_linux-64=2.38
  - libboost=1.73.0
  - libffi=3.3
  - libgcc-ng=11.2.0
  - libgfortran-ng=7.5.0
  - libgfortran4=7.5.0
  - libgomp=11.2.0
  - libpng=1.6.37
  - libprotobuf=3.17.2
  - libsodium=1.0.18
  - libstdcxx-ng=11.2.0
  - libtiff=4.2.0
  - libuuid=1.0.3
  - libwebp-base=1.2.2
  - libxcb=1.15
  - libxml2=2.9.14
  - lz4-c=1.9.3
  - markdown=3.3.4
  - markupsafe=2.0.1
  - matplotlib=3.3.4
  - matplotlib-base=3.3.4
  - mistune=0.8.4
  - mkl=2020.2
  - mkl-service=2.3.0
  - mkl_fft=1.3.0
  - mkl_random=1.1.1
  - multidict=5.1.0
  - nbclassic=0.2.6
  - nbclient=0.5.3
  - nbconvert=6.0.7
  - nbformat=5.1.3
  - ncurses=6.3
  - nest-asyncio=1.5.1
  - ninja=1.10.2
  - ninja-base=1.10.2
  - notebook=6.4.3
  - numpy=1.19.2
  - numpy-base=1.19.2
  - oauthlib=3.2.0
  - olefile=0.46
  - openjpeg=2.4.0
  - openssl=1.1.1o
  - opentsne=0.6.0
  - opt_einsum=3.3.0
  - packaging=21.3
  - pandas=1.1.5
  - pandoc=2.12
  - pandocfilters=1.5.0
  - parso=0.8.3
  - pcre=8.45
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=8.3.1
  - pip=21.2.2
  - pixman=0.40.0
  - prometheus_client=0.13.1
  - prompt-toolkit=3.0.20
  - protobuf=3.17.2
  - ptyprocess=0.7.0
  - py-boost=1.73.0
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.8
  - pycparser=2.21
  - pygments=2.11.2
  - pyjwt=2.1.0
  - pyopenssl=21.0.0
  - pyparsing=3.0.4
  - pyqt=5.9.2
  - pyrsistent=0.17.3
  - pysocks=1.7.1
  - python=3.6.13
  - python-dateutil=2.8.2
  - python_abi=3.6
  - pytorch=0.4.1
  - pytz=2021.3
  - pyu2f=0.1.5
  - pyzmq=22.2.1
  - qt=5.9.7
  - rdkit=2020.09.1.0
  - readline=8.1.2
  - requests=2.27.1
  - requests-oauthlib=1.3.0
  - rsa=4.7.2
  - scikit-learn=0.20.0
  - scipy=1.5.2
  - seaborn=0.11.2
  - send2trash=1.8.0
  - setuptools=58.0.4
  - sip=4.19.8
  - six=1.16.0
  - sniffio=1.2.0
  - sqlite=3.38.5
  - tbb=2021.6.0
  - tensorboard=2.4.0
  - tensorboard-plugin-wit=1.6.0
  - tensorflow=2.2.0
  - tensorflow-base=2.2.0
  - tensorflow-estimator=2.6.0
  - termcolor=1.1.0
  - terminado=0.9.4
  - testpath=0.5.0
  - tk=8.6.12
  - torchvision=0.2.1
  - tornado=6.1
  - tqdm=4.63.0
  - traitlets=4.3.3
  - typing-extensions=4.1.1
  - typing_extensions=4.1.1
  - urllib3=1.26.8
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - werkzeug=2.0.3
  - wheel=0.37.1
  - wrapt=1.12.1
  - xz=5.2.5
  - yarl=1.6.3
  - zeromq=4.3.4
  - zipp=3.6.0
  - zlib=1.2.12
  - zstd=1.4.9
  - pip:
    - importlib-resources==5.4.0
    - joblib==1.1.0
    - tensorboardx==1.8
    - torchtext==0.3.1
