SOLVENTS = {
    "CC#N": "acetonitrile",
    "C[N+](=O)[O-]": "nitromethane",
    "Cc1ccccc1": "toluene",
    "c1ccccc1": "benzene",
    "Cc1ccccc1C": "o-xylene",
    "Cc1cccc(C)c1": "m-xylene",
    "Cc1ccc(C)cc1": "p-xylene",
    "c1ccncc1": "pyridine",
    "Clc1ccccc1": "chlorobenzene",
    "Clc1ccccc1Cl": "1,2-dichlorobenzene",
    "ClCCl": "dichloromethane",
    "CC(Cl)Cl": "1,1-dichloroethane",
    "ClCCCl": "1,2-dichloroethane",
    "ClC(Cl)Cl": "chloroform",
    "ClC(Cl)(Cl)Cl": "carbon tetrachloride",
    "C1CCOC1": "THF",
    "CC1CCCO1": "2-methyl-THF",
    "C1COCCO1": "1,4-dioxane",
    "CCCCC": "pentane",
    "CCCCCC": "hexane",
    "CCCCCCC": "heptane",
    "C1CCCCC1": "cyclohexane",
    "C1CCCC1": "cyclopentane",
    "CO": "methanol",
    "CCO": "ethanol",
    "CCCO": "1-propanol",
    "CCCCO": "n-butanol",
    "CC(C)O": "isopropanol",
    "CC(C)(C)O": "tert-butanol",
    "CC(C)CO": "isobutanol",
    "CC(C)=O": "acetone",
    "CCC(C)=O": "butanone",
    "CN(C)C=O": "DMF",
    "CN1CCCC1=O": "N-methyl-2-pyrrolidone",
    "CNC(C)=O": "N-methylacetamide",
    "CC(=O)N(C)C": "dimethylacetamide",
    "CS(C)=O": "DMSO",
    "CN(C)P(=O)(N(C)C)N(C)C": "HMPA",
    "OCCO": "ethylene glycol",
    "CC(=O)O": "acetic acid",
    "O=C(O)C(F)(F)F": "TFA",
    "CCOCC": "diethyl ether",
    "COCCOC": "1,2-DME",
    "COC(C)(C)C": "Methyl tert-butyl ether",
    "CCOC(C)=O": "ethyl acetate",
    "S=C=S": "carbon disulfide"
}
