seed: 123456
data:
    train:
        path_src: data/tokenized/MIT_mixed/src-train.txt
        path_tgt: data/tokenized/MIT_mixed/tgt-train.txt
    valid:
        path_src: data/tokenized/MIT_mixed/src-val.txt
        path_tgt: data/tokenized/MIT_mixed/tgt-val.txt
save_data: data/tokenized/MIT_mixed/MIT_mixed
src_vocab: data/tokenized/MIT_mixed/MIT_mixed/MIT_mixed.vocab.src
tgt_vocab: data/tokenized/MIT_mixed/MIT_mixed/MIT_mixed.vocab.tgt

# Vocabulary building
src_seq_length: 1000
tgt_seq_length: 1000
src_vocab_size: 1000
tgt_vocab_size: 1000
share_vocab: True
overwrite: True

# Model training
save_checkpoint_steps: 10000
keep_checkpoint: 20
train_steps: 500000
valid_steps: 10000
report_every: 10

decoder_type: transformer
encoder_type: transformer
word_vec_size: 256
hidden_size: 256
layers: 4
transformer_ff: 2048
heads: 8

accum_count: 4
optim: adam
adam_beta1: 0.9
adam_beta2: 0.998
decay_method: noam
warmup_steps: 8000
learning_rate: 2.0
max_grad_norm: 0.0

batch_size: 4096
batch_type: tokens
normalization: tokens
dropout: 0.1
label_smoothing: 0.0

param_init: 0.0
param_init_glorot: True
position_encoding: True
share_embeddings: True
global_attention: general
global_attention_function: softmax
self_attn_type: scaled-dot

#world_size: 4
#gpu_ranks:
#- 0
#- 1
#- 2
#- 3